// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApiAssetPairRateBaseModel
    {
        /// <summary>
        /// Initializes a new instance of the ApiAssetPairRateBaseModel class.
        /// </summary>
        public ApiAssetPairRateBaseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiAssetPairRateBaseModel class.
        /// </summary>
        public ApiAssetPairRateBaseModel(string id = default(string), double? bid = default(double?), double? ask = default(double?))
        {
            Id = id;
            Bid = bid;
            Ask = ask;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Bid")]
        public double? Bid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Ask")]
        public double? Ask { get; set; }

    }
}
