// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BccTransactionResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the BccTransactionResponseModel
        /// class.
        /// </summary>
        public BccTransactionResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BccTransactionResponseModel
        /// class.
        /// </summary>
        public BccTransactionResponseModel(string transaction = default(string), string inputs = default(string))
        {
            Transaction = transaction;
            Inputs = inputs;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Transaction")]
        public string Transaction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Inputs")]
        public string Inputs { get; set; }

    }
}
