// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientBalancesModel
    {
        /// <summary>
        /// Initializes a new instance of the ClientBalancesModel class.
        /// </summary>
        public ClientBalancesModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientBalancesModel class.
        /// </summary>
        public ClientBalancesModel(double? tradingWallet = default(double?), double? privateWallets = default(double?), double? marginWallets = default(double?))
        {
            TradingWallet = tradingWallet;
            PrivateWallets = privateWallets;
            MarginWallets = marginWallets;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TradingWallet")]
        public double? TradingWallet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrivateWallets")]
        public double? PrivateWallets { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarginWallets")]
        public double? MarginWallets { get; set; }

    }
}
