// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClientDialog
    {
        /// <summary>
        /// Initializes a new instance of the ClientDialog class.
        /// </summary>
        public ClientDialog()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientDialog class.
        /// </summary>
        /// <param name="type">Possible values include: 'Info', 'Warning',
        /// 'Question'</param>
        public ClientDialog(System.Guid? id = default(System.Guid?), string type = default(string), string caption = default(string), string text = default(string), IList<ClientDialogButtonModel> buttons = default(IList<ClientDialogButtonModel>))
        {
            Id = id;
            Type = type;
            Caption = caption;
            Text = text;
            Buttons = buttons;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Info', 'Warning', 'Question'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Caption")]
        public string Caption { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Text")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Buttons")]
        public IList<ClientDialogButtonModel> Buttons { get; set; }

    }
}
