// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetAssetPairRateModel
    {
        /// <summary>
        /// Initializes a new instance of the GetAssetPairRateModel class.
        /// </summary>
        public GetAssetPairRateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetAssetPairRateModel class.
        /// </summary>
        public GetAssetPairRateModel(ApiAssetPairRateModel rate = default(ApiAssetPairRateModel))
        {
            Rate = rate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Rate")]
        public ApiAssetPairRateModel Rate { get; set; }

    }
}
