// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetAssetPairDetailedRateModel
    {
        /// <summary>
        /// Initializes a new instance of the GetAssetPairDetailedRateModel
        /// class.
        /// </summary>
        public GetAssetPairDetailedRateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetAssetPairDetailedRateModel
        /// class.
        /// </summary>
        public GetAssetPairDetailedRateModel(System.DateTime? fixingTime = default(System.DateTime?), double? lastPrice = default(double?), AssetPairDetailedRateModel rate = default(AssetPairDetailedRateModel), System.DateTime? startTime = default(System.DateTime?), System.DateTime? endTime = default(System.DateTime?))
        {
            FixingTime = fixingTime;
            LastPrice = lastPrice;
            Rate = rate;
            StartTime = startTime;
            EndTime = endTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FixingTime")]
        public System.DateTime? FixingTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastPrice")]
        public double? LastPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Rate")]
        public AssetPairDetailedRateModel Rate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartTime")]
        public System.DateTime? StartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndTime")]
        public System.DateTime? EndTime { get; set; }

    }
}
