// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class KycDocumentsModelDeprecated
    {
        /// <summary>
        /// Initializes a new instance of the KycDocumentsModelDeprecated
        /// class.
        /// </summary>
        public KycDocumentsModelDeprecated()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KycDocumentsModelDeprecated
        /// class.
        /// </summary>
        /// <param name="idType">Possible values include: 'Unknown',
        /// 'Passport', 'Id', 'DrivingLicense'</param>
        public KycDocumentsModelDeprecated(string type = default(string), string ext = default(string), string data = default(string), string idType = default(string))
        {
            Type = type;
            Ext = ext;
            Data = data;
            IdType = idType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Ext")]
        public string Ext { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public string Data { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Passport', 'Id',
        /// 'DrivingLicense'
        /// </summary>
        [JsonProperty(PropertyName = "IdType")]
        public string IdType { get; set; }

    }
}
