// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class KycForAssetResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the KycForAssetResponseModel class.
        /// </summary>
        public KycForAssetResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KycForAssetResponseModel class.
        /// </summary>
        /// <param name="userKycStatus">Possible values include:
        /// 'NeedToFillData', 'Pending', 'Ok', 'RestrictedArea'</param>
        public KycForAssetResponseModel(string userKycStatus = default(string), bool? kycNeeded = default(bool?))
        {
            UserKycStatus = userKycStatus;
            KycNeeded = kycNeeded;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'NeedToFillData', 'Pending',
        /// 'Ok', 'RestrictedArea'
        /// </summary>
        [JsonProperty(PropertyName = "UserKycStatus")]
        public string UserKycStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KycNeeded")]
        public bool? KycNeeded { get; set; }

    }
}
