// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MarginSwiftCashOutReqModel
    {
        /// <summary>
        /// Initializes a new instance of the MarginSwiftCashOutReqModel class.
        /// </summary>
        public MarginSwiftCashOutReqModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MarginSwiftCashOutReqModel class.
        /// </summary>
        public MarginSwiftCashOutReqModel(string marginAccountId = default(string), double? amount = default(double?), string bic = default(string), string accNumber = default(string), string accName = default(string), string accHolderAddress = default(string), string bankName = default(string), string accHolderCountry = default(string), string accHolderZipCode = default(string), string accHolderCity = default(string), string correspondentAccount = default(string))
        {
            MarginAccountId = marginAccountId;
            Amount = amount;
            Bic = bic;
            AccNumber = accNumber;
            AccName = accName;
            AccHolderAddress = accHolderAddress;
            BankName = bankName;
            AccHolderCountry = accHolderCountry;
            AccHolderZipCode = accHolderZipCode;
            AccHolderCity = accHolderCity;
            CorrespondentAccount = correspondentAccount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarginAccountId")]
        public string MarginAccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Bic")]
        public string Bic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccNumber")]
        public string AccNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccName")]
        public string AccName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderAddress")]
        public string AccHolderAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BankName")]
        public string BankName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderCountry")]
        public string AccHolderCountry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderZipCode")]
        public string AccHolderZipCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderCity")]
        public string AccHolderCity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CorrespondentAccount")]
        public string CorrespondentAccount { get; set; }

    }
}
