// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainTransferToTrustedWalletModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OffchainTransferToTrustedWalletModel class.
        /// </summary>
        public OffchainTransferToTrustedWalletModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OffchainTransferToTrustedWalletModel class.
        /// </summary>
        public OffchainTransferToTrustedWalletModel(string walletId = default(string), string asset = default(string), double? amount = default(double?), string prevTempPrivateKey = default(string))
        {
            WalletId = walletId;
            Asset = asset;
            Amount = amount;
            PrevTempPrivateKey = prevTempPrivateKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WalletId")]
        public string WalletId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrevTempPrivateKey")]
        public string PrevTempPrivateKey { get; set; }

    }
}
