// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainTradeRespModel
    {
        /// <summary>
        /// Initializes a new instance of the OffchainTradeRespModel class.
        /// </summary>
        public OffchainTradeRespModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainTradeRespModel class.
        /// </summary>
        /// <param name="operationResult">Possible values include: 'Transfer',
        /// 'CreateChannel', 'ClientCommitment'</param>
        public OffchainTradeRespModel(string transferId = default(string), string transactionHex = default(string), string operationResult = default(string))
        {
            TransferId = transferId;
            TransactionHex = transactionHex;
            OperationResult = operationResult;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransferId")]
        public string TransferId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransactionHex")]
        public string TransactionHex { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Transfer', 'CreateChannel',
        /// 'ClientCommitment'
        /// </summary>
        [JsonProperty(PropertyName = "OperationResult")]
        public string OperationResult { get; set; }

    }
}
