// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainCashoutSwiftModel
    {
        /// <summary>
        /// Initializes a new instance of the OffchainCashoutSwiftModel class.
        /// </summary>
        public OffchainCashoutSwiftModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainCashoutSwiftModel class.
        /// </summary>
        public OffchainCashoutSwiftModel(double? amount = default(double?), string asset = default(string), string prevTempPrivateKey = default(string), string bic = default(string), string accNumber = default(string), string accName = default(string), string accHolderAddress = default(string), string bankName = default(string), string accHolderCountry = default(string), string accHolderZipCode = default(string), string accHolderCity = default(string), string correspondentAccount = default(string))
        {
            Amount = amount;
            Asset = asset;
            PrevTempPrivateKey = prevTempPrivateKey;
            Bic = bic;
            AccNumber = accNumber;
            AccName = accName;
            AccHolderAddress = accHolderAddress;
            BankName = bankName;
            AccHolderCountry = accHolderCountry;
            AccHolderZipCode = accHolderZipCode;
            AccHolderCity = accHolderCity;
            CorrespondentAccount = correspondentAccount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrevTempPrivateKey")]
        public string PrevTempPrivateKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Bic")]
        public string Bic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccNumber")]
        public string AccNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccName")]
        public string AccName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderAddress")]
        public string AccHolderAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BankName")]
        public string BankName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderCountry")]
        public string AccHolderCountry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderZipCode")]
        public string AccHolderZipCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderCity")]
        public string AccHolderCity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CorrespondentAccount")]
        public string CorrespondentAccount { get; set; }

    }
}
