// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OperationModel
    {
        /// <summary>
        /// Initializes a new instance of the OperationModel class.
        /// </summary>
        public OperationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OperationModel class.
        /// </summary>
        public OperationModel(string assetPair = default(string), string asset = default(string), string addressTo = default(string), double? volume = default(double?), bool? isLimit = default(bool?), double? price = default(double?))
        {
            AssetPair = assetPair;
            Asset = asset;
            AddressTo = addressTo;
            Volume = volume;
            IsLimit = isLimit;
            Price = price;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressTo")]
        public string AddressTo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double? Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsLimit")]
        public bool? IsLimit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double? Price { get; set; }

    }
}
