// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PagingInfoModel
    {
        /// <summary>
        /// Initializes a new instance of the PagingInfoModel class.
        /// </summary>
        public PagingInfoModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PagingInfoModel class.
        /// </summary>
        public PagingInfoModel(int? elementCount = default(int?), string nextPage = default(string), IList<string> previousPages = default(IList<string>), int? currentPage = default(int?), int? navigateToPageIndex = default(int?))
        {
            ElementCount = elementCount;
            NextPage = nextPage;
            PreviousPages = previousPages;
            CurrentPage = currentPage;
            NavigateToPageIndex = navigateToPageIndex;
            CustomInit();
        }

        public PagingInfoModel(int elementCount)
        {
            ElementCount = elementCount;
            NextPage = "";
            PreviousPages = new List<string>();
            CurrentPage = 0;
            NavigateToPageIndex = 0;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ElementCount")]
        public int? ElementCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NextPage")]
        public string NextPage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PreviousPages")]
        public IList<string> PreviousPages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CurrentPage")]
        public int? CurrentPage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NavigateToPageIndex")]
        public int? NavigateToPageIndex { get; set; }

    }
}
