// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProfilePersonalData
    {
        /// <summary>
        /// Initializes a new instance of the ProfilePersonalData class.
        /// </summary>
        public ProfilePersonalData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProfilePersonalData class.
        /// </summary>
        public ProfilePersonalData(string clientId = default(string), string email = default(string), string firstName = default(string), string lastName = default(string), System.DateTime? registered = default(System.DateTime?), string avatarUrl = default(string), string address = default(string), string website = default(string), string shortBio = default(string), string facebook = default(string), string twitter = default(string), string github = default(string))
        {
            ClientId = clientId;
            Email = email;
            FirstName = firstName;
            LastName = lastName;
            Registered = registered;
            AvatarUrl = avatarUrl;
            Address = address;
            Website = website;
            ShortBio = shortBio;
            Facebook = facebook;
            Twitter = twitter;
            Github = github;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Registered")]
        public System.DateTime? Registered { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AvatarUrl")]
        public string AvatarUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Website")]
        public string Website { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShortBio")]
        public string ShortBio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Facebook")]
        public string Facebook { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Twitter")]
        public string Twitter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Github")]
        public string Github { get; set; }

    }
}
