// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PublicPersonalData
    {
        /// <summary>
        /// Initializes a new instance of the PublicPersonalData class.
        /// </summary>
        public PublicPersonalData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PublicPersonalData class.
        /// </summary>
        public PublicPersonalData(string id = default(string), string email = default(string), string firstName = default(string), string country = default(string), string registered = default(string))
        {
            Id = id;
            Email = email;
            FirstName = firstName;
            Country = country;
            Registered = registered;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Registered")]
        public string Registered { get; set; }

    }
}
