// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RequestVoiceCallModel
    {
        /// <summary>
        /// Initializes a new instance of the RequestVoiceCallModel class.
        /// </summary>
        public RequestVoiceCallModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RequestVoiceCallModel class.
        /// </summary>
        public RequestVoiceCallModel(string phoneNumber = default(string), string email = default(string))
        {
            PhoneNumber = phoneNumber;
            Email = email;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PhoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

    }
}
