// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TrustedHashModel
    {
        /// <summary>
        /// Initializes a new instance of the TrustedHashModel class.
        /// </summary>
        public TrustedHashModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TrustedHashModel class.
        /// </summary>
        public TrustedHashModel(string asset = default(string), double? volume = default(double?))
        {
            Asset = asset;
            Volume = volume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double? Volume { get; set; }

    }
}
