// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;
    using TestsCore.TestsData;

    public partial class UpdateProfileInfoRequest
    {
        /// <summary>
        /// Initializes a new instance of the UpdateProfileInfoRequest class.
        /// </summary>
        public UpdateProfileInfoRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateProfileInfoRequest class.
        /// </summary>
        public UpdateProfileInfoRequest(string clientId = default(string), string email = default(string), string address = default(string), string website = default(string), string shortBio = default(string), string facebook = default(string), string twitter = default(string), string github = default(string))
        {
            ClientId = clientId;
            Email = email;
            Address = address;
            Website = website;
            ShortBio = shortBio;
            Facebook = facebook;
            Twitter = twitter;
            Github = github;
            CustomInit();
        }

        public UpdateProfileInfoRequest(string clientId)
        {
            ClientId = clientId;
            Email = TestData.GenerateEmail();
            Address = TestData.GenerateString(8);
            Website = TestData.GenerateString(8);
            ShortBio = TestData.GenerateString(8);
            Facebook = TestData.GenerateString(8);
            Twitter = TestData.GenerateString(8);
            Github = TestData.GenerateString(8);
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Website")]
        public string Website { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShortBio")]
        public string ShortBio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Facebook")]
        public string Facebook { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Twitter")]
        public string Twitter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Github")]
        public string Github { get; set; }

    }
}
