// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExchangeOperationResult
    {
        /// <summary>
        /// Initializes a new instance of the ExchangeOperationResult class.
        /// </summary>
        public ExchangeOperationResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExchangeOperationResult class.
        /// </summary>
        public ExchangeOperationResult(int? code = default(int?), string message = default(string), string transactionId = default(string))
        {
            Code = code;
            Message = message;
            TransactionId = transactionId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public int? Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionId")]
        public string TransactionId { get; set; }

    }
}
