// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.Registration.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountsRegistrationResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the AccountsRegistrationResponseModel
        /// class.
        /// </summary>
        public AccountsRegistrationResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountsRegistrationResponseModel
        /// class.
        /// </summary>
        public AccountsRegistrationResponseModel(bool canCashInViaBankCard, bool swiftDepositEnabled, ClientAccountInformationModel account = default(ClientAccountInformationModel), string token = default(string), string notificationsId = default(string), ApiPersonalDataModel personalData = default(ApiPersonalDataModel))
        {
            Account = account;
            Token = token;
            NotificationsId = notificationsId;
            PersonalData = personalData;
            CanCashInViaBankCard = canCashInViaBankCard;
            SwiftDepositEnabled = swiftDepositEnabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Account")]
        public ClientAccountInformationModel Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Token")]
        public string Token { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NotificationsId")]
        public string NotificationsId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PersonalData")]
        public ApiPersonalDataModel PersonalData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CanCashInViaBankCard")]
        public bool CanCashInViaBankCard { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SwiftDepositEnabled")]
        public bool SwiftDepositEnabled { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Account != null)
            {
                Account.Validate();
            }
        }
    }
}
