// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.Registration.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApiPersonalDataModel
    {
        /// <summary>
        /// Initializes a new instance of the ApiPersonalDataModel class.
        /// </summary>
        public ApiPersonalDataModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiPersonalDataModel class.
        /// </summary>
        public ApiPersonalDataModel(string fullName = default(string), string firstName = default(string), string lastName = default(string), string email = default(string), string phone = default(string), string country = default(string), string address = default(string), string city = default(string), string zip = default(string))
        {
            FullName = fullName;
            FirstName = firstName;
            LastName = lastName;
            Email = email;
            Phone = phone;
            Country = country;
            Address = address;
            City = city;
            Zip = zip;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FullName")]
        public string FullName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Zip")]
        public string Zip { get; set; }

    }
}
