// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.Registration.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AuthenticateModel
    {
        /// <summary>
        /// Initializes a new instance of the AuthenticateModel class.
        /// </summary>
        public AuthenticateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AuthenticateModel class.
        /// </summary>
        public AuthenticateModel(string email = default(string), string password = default(string), string clientInfo = default(string), string partnerId = default(string), string userAgent = default(string), string ip = default(string))
        {
            Email = email;
            Password = password;
            ClientInfo = clientInfo;
            PartnerId = partnerId;
            UserAgent = userAgent;
            Ip = ip;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientInfo")]
        public string ClientInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerId")]
        public string PartnerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserAgent")]
        public string UserAgent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Ip")]
        public string Ip { get; set; }

    }
}
