// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.Registration.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IAuthorizationLogRecord
    {
        /// <summary>
        /// Initializes a new instance of the IAuthorizationLogRecord class.
        /// </summary>
        public IAuthorizationLogRecord()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IAuthorizationLogRecord class.
        /// </summary>
        public IAuthorizationLogRecord(System.DateTime dateTime, string clientId = default(string), string userAgent = default(string), string ip = default(string), string clientInfo = default(string), string sessionToken = default(string), string country = default(string), string city = default(string), string isp = default(string))
        {
            ClientId = clientId;
            DateTime = dateTime;
            UserAgent = userAgent;
            Ip = ip;
            ClientInfo = clientInfo;
            SessionToken = sessionToken;
            Country = country;
            City = city;
            Isp = isp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateTime")]
        public System.DateTime DateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserAgent")]
        public string UserAgent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Ip")]
        public string Ip { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientInfo")]
        public string ClientInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SessionToken")]
        public string SessionToken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Isp")]
        public string Isp { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
