// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.Registration.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IRegistrationLogEvent
    {
        /// <summary>
        /// Initializes a new instance of the IRegistrationLogEvent class.
        /// </summary>
        public IRegistrationLogEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IRegistrationLogEvent class.
        /// </summary>
        public IRegistrationLogEvent(string id = default(string), System.DateTime? dateTime = default(System.DateTime?), string clientId = default(string), string email = default(string), string fullName = default(string), string contactPhone = default(string), string deviceInfo = default(string), string country = default(string), string city = default(string), string ip = default(string), string isp = default(string), string referer = default(string))
        {
            Id = id;
            DateTime = dateTime;
            ClientId = clientId;
            Email = email;
            FullName = fullName;
            ContactPhone = contactPhone;
            DeviceInfo = deviceInfo;
            Country = country;
            City = city;
            Ip = ip;
            Isp = isp;
            Referer = referer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateTime")]
        public System.DateTime? DateTime { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FullName")]
        public string FullName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactPhone")]
        public string ContactPhone { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeviceInfo")]
        public string DeviceInfo { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public string City { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Ip")]
        public string Ip { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Isp")]
        public string Isp { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Referer")]
        public string Referer { get; private set; }

    }
}
