// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.ApiV2.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AffiliateStatisticsResponse
    {
        /// <summary>
        /// Initializes a new instance of the AffiliateStatisticsResponse
        /// class.
        /// </summary>
        public AffiliateStatisticsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AffiliateStatisticsResponse
        /// class.
        /// </summary>
        public AffiliateStatisticsResponse(int referralsCount, double totalBonus, double totalTradeVolume)
        {
            ReferralsCount = referralsCount;
            TotalBonus = totalBonus;
            TotalTradeVolume = totalTradeVolume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReferralsCount")]
        public int ReferralsCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalBonus")]
        public double TotalBonus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalTradeVolume")]
        public double TotalTradeVolume { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
