// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.ApiV2.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AssetCategoriesModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetCategoriesModel class.
        /// </summary>
        public AssetCategoriesModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetCategoriesModel class.
        /// </summary>
        public AssetCategoriesModel(IList<AssetCategoryModel> assetCategories)
        {
            AssetCategories = assetCategories;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetCategories")]
        public IList<AssetCategoryModel> AssetCategories { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AssetCategories == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AssetCategories");
            }
            if (AssetCategories != null)
            {
                foreach (var element in AssetCategories)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
