// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.ApiV2.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetRespModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetRespModel class.
        /// </summary>
        public AssetRespModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetRespModel class.
        /// </summary>
        public AssetRespModel(AssetModel asset)
        {
            Asset = asset;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public AssetModel Asset { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Asset == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Asset");
            }
            if (Asset != null)
            {
                Asset.Validate();
            }
        }
    }
}
