// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.ApiV2.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AuthRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the AuthRequestModel class.
        /// </summary>
        public AuthRequestModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AuthRequestModel class.
        /// </summary>
        public AuthRequestModel(string email, string password, string clientInfo, string partnerId)
        {
            Email = email;
            Password = password;
            ClientInfo = clientInfo;
            PartnerId = partnerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientInfo")]
        public string ClientInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerId")]
        public string PartnerId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Email == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Email");
            }
            if (Password == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Password");
            }
            if (ClientInfo == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ClientInfo");
            }
            if (PartnerId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PartnerId");
            }
        }
    }
}
