// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.ApiV2.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for DialogConditionType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DialogConditionType
    {
        [EnumMember(Value = "Pretrade")]
        Pretrade,
        [EnumMember(Value = "Predeposit")]
        Predeposit
    }
    internal static class DialogConditionTypeEnumExtension
    {
        internal static string ToSerializedValue(this DialogConditionType? value)
        {
            return value == null ? null : ((DialogConditionType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this DialogConditionType value)
        {
            switch( value )
            {
                case DialogConditionType.Pretrade:
                    return "Pretrade";
                case DialogConditionType.Predeposit:
                    return "Predeposit";
            }
            return null;
        }

        internal static DialogConditionType? ParseDialogConditionType(this string value)
        {
            switch( value )
            {
                case "Pretrade":
                    return DialogConditionType.Pretrade;
                case "Predeposit":
                    return DialogConditionType.Predeposit;
            }
            return null;
        }
    }
}
