// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.ApiV2.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for FundsOperation.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FundsOperation
    {
        [EnumMember(Value = "Deposit")]
        Deposit,
        [EnumMember(Value = "Withdraw")]
        Withdraw
    }
    internal static class FundsOperationEnumExtension
    {
        internal static string ToSerializedValue(this FundsOperation? value)
        {
            return value == null ? null : ((FundsOperation)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this FundsOperation value)
        {
            switch( value )
            {
                case FundsOperation.Deposit:
                    return "Deposit";
                case FundsOperation.Withdraw:
                    return "Withdraw";
            }
            return null;
        }

        internal static FundsOperation? ParseFundsOperation(this string value)
        {
            switch( value )
            {
                case "Deposit":
                    return FundsOperation.Deposit;
                case "Withdraw":
                    return FundsOperation.Withdraw;
            }
            return null;
        }
    }
}
