// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.ApiV2.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Response model containing information about current password recovery
    /// state.
    /// </summary>
    public partial class RecoveryStatusResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the RecoveryStatusResponseModel
        /// class.
        /// </summary>
        public RecoveryStatusResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RecoveryStatusResponseModel
        /// class.
        /// </summary>
        /// <param name="challenge">Current challenge provided for client.
        /// Possible values include: 'Unknown', 'Sms', 'Email', 'Selfie',
        /// 'Words', 'Device', 'Pin', 'Undefined'</param>
        /// <param name="overallProgress">Overall progress status of password
        /// recovery. Possible values include: 'Ongoing', 'WaitingForSupport',
        /// 'Frozen', 'Suspended', 'Allowed', 'Undefined'</param>
        /// <param name="challengeInfo">Information about challenge.</param>
        public RecoveryStatusResponseModel(Challenge challenge, Progress overallProgress, string challengeInfo)
        {
            Challenge = challenge;
            OverallProgress = overallProgress;
            ChallengeInfo = challengeInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets current challenge provided for client. Possible values
        /// include: 'Unknown', 'Sms', 'Email', 'Selfie', 'Words', 'Device',
        /// 'Pin', 'Undefined'
        /// </summary>
        [JsonProperty(PropertyName = "Challenge")]
        public Challenge Challenge { get; set; }

        /// <summary>
        /// Gets or sets overall progress status of password recovery. Possible
        /// values include: 'Ongoing', 'WaitingForSupport', 'Frozen',
        /// 'Suspended', 'Allowed', 'Undefined'
        /// </summary>
        [JsonProperty(PropertyName = "OverallProgress")]
        public Progress OverallProgress { get; set; }

        /// <summary>
        /// Gets or sets information about challenge.
        /// </summary>
        [JsonProperty(PropertyName = "ChallengeInfo")]
        public string ChallengeInfo { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ChallengeInfo == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ChallengeInfo");
            }
        }
    }
}
