// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.ApiV2.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WalletAssetBalanceModel
    {
        /// <summary>
        /// Initializes a new instance of the WalletAssetBalanceModel class.
        /// </summary>
        public WalletAssetBalanceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WalletAssetBalanceModel class.
        /// </summary>
        public WalletAssetBalanceModel(string id, string name, string type, string description, ClientBalanceResponseModel balances, string apiKey)
        {
            Id = id;
            Name = name;
            Type = type;
            Description = description;
            Balances = balances;
            ApiKey = apiKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Balances")]
        public ClientBalanceResponseModel Balances { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApiKey")]
        public string ApiKey { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
            if (Description == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Description");
            }
            if (Balances == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Balances");
            }
            if (ApiKey == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ApiKey");
            }
            if (Balances != null)
            {
                Balances.Validate();
            }
        }
    }
}
