// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.ClientAccount.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AppUsageSettings
    {
        /// <summary>
        /// Initializes a new instance of the AppUsageSettings class.
        /// </summary>
        public AppUsageSettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppUsageSettings class.
        /// </summary>
        public AppUsageSettings(string lastUsedGraphPeriod = default(string))
        {
            LastUsedGraphPeriod = lastUsedGraphPeriod;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastUsedGraphPeriod")]
        public string LastUsedGraphPeriod { get; set; }

    }
}
