// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.ClientAccount.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BannedClient
    {
        /// <summary>
        /// Initializes a new instance of the BannedClient class.
        /// </summary>
        public BannedClient()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BannedClient class.
        /// </summary>
        public BannedClient(string clientId = default(string))
        {
            ClientId = clientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

    }
}
