// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.ClientAccount.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientRegistrationModel
    {
        /// <summary>
        /// Initializes a new instance of the ClientRegistrationModel class.
        /// </summary>
        public ClientRegistrationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientRegistrationModel class.
        /// </summary>
        public ClientRegistrationModel(string email = default(string), string phone = default(string), string password = default(string), string partnerId = default(string))
        {
            Email = email;
            Phone = phone;
            Password = password;
            PartnerId = partnerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerId")]
        public string PartnerId { get; set; }

    }
}
