// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.ClientAccount.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateWalletRequest
    {
        /// <summary>
        /// Initializes a new instance of the CreateWalletRequest class.
        /// </summary>
        public CreateWalletRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateWalletRequest class.
        /// </summary>
        /// <param name="type">Possible values include: 'Trusted',
        /// 'Trading'</param>
        public CreateWalletRequest(WalletType type, string clientId = default(string), string name = default(string), string description = default(string))
        {
            ClientId = clientId;
            Type = type;
            Name = name;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Trusted', 'Trading'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public WalletType Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
