// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.ClientAccount.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IPartnerAccountPolicy
    {
        /// <summary>
        /// Initializes a new instance of the IPartnerAccountPolicy class.
        /// </summary>
        public IPartnerAccountPolicy()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IPartnerAccountPolicy class.
        /// </summary>
        public IPartnerAccountPolicy(bool useDifferentCredentials, string publicId = default(string))
        {
            PublicId = publicId;
            UseDifferentCredentials = useDifferentCredentials;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PublicId")]
        public string PublicId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UseDifferentCredentials")]
        public bool UseDifferentCredentials { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
