// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.ClientAccount.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IsUsaUserSettings
    {
        /// <summary>
        /// Initializes a new instance of the IsUsaUserSettings class.
        /// </summary>
        public IsUsaUserSettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IsUsaUserSettings class.
        /// </summary>
        public IsUsaUserSettings(bool isUSA)
        {
            IsUSA = isUSA;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsUSA")]
        public bool IsUSA { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
