// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace LykkeAutomationPrivate.Models.ClientAccount.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Partner
    {
        /// <summary>
        /// Initializes a new instance of the Partner class.
        /// </summary>
        public Partner()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Partner class.
        /// </summary>
        public Partner(int registeredUsersCount, string internalId = default(string), string publicId = default(string), string name = default(string), string assetPrefix = default(string))
        {
            InternalId = internalId;
            PublicId = publicId;
            Name = name;
            AssetPrefix = assetPrefix;
            RegisteredUsersCount = registeredUsersCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InternalId")]
        public string InternalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PublicId")]
        public string PublicId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPrefix")]
        public string AssetPrefix { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegisteredUsersCount")]
        public int RegisteredUsersCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
