// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Response class for IsAlive request.
    /// </summary>
    public partial class IsAliveModel
    {
        /// <summary>
        /// Initializes a new instance of the IsAliveModel class.
        /// </summary>
        public IsAliveModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IsAliveModel class.
        /// </summary>
        /// <param name="version">The version of the service.</param>
        /// <param name="env">The environment of the service (pod
        /// name).</param>
        /// <param name="isDebug">Indicating whether this instance is in debug
        /// or production mode.</param>
        /// <param name="issueIndicators">The possible health issues of the
        /// service.</param>
        public IsAliveModel(string version, string env, bool isDebug, IList<IssueModel> issueIndicators)
        {
            Version = version;
            Env = env;
            IsDebug = isDebug;
            IssueIndicators = issueIndicators;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the version of the service.
        /// </summary>
        [JsonProperty(PropertyName = "Version")]
        public string Version { get; set; }

        /// <summary>
        /// Gets or sets the environment of the service (pod name).
        /// </summary>
        [JsonProperty(PropertyName = "Env")]
        public string Env { get; set; }

        /// <summary>
        /// Gets or sets indicating whether this instance is in debug or
        /// production mode.
        /// </summary>
        [JsonProperty(PropertyName = "IsDebug")]
        public bool IsDebug { get; set; }

        /// <summary>
        /// Gets or sets the possible health issues of the service.
        /// </summary>
        [JsonProperty(PropertyName = "IssueIndicators")]
        public IList<IssueModel> IssueIndicators { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Version == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Version");
            }
            if (Env == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Env");
            }
            if (IssueIndicators == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "IssueIndicators");
            }
            if (IssueIndicators != null)
            {
                foreach (var element in IssueIndicators)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
