// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderStatus
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "Placed")]
        Placed,
        [EnumMember(Value = "PartiallyMatched")]
        PartiallyMatched,
        [EnumMember(Value = "Matched")]
        Matched,
        [EnumMember(Value = "Pending")]
        Pending,
        [EnumMember(Value = "Cancelled")]
        Cancelled,
        [EnumMember(Value = "Replaced")]
        Replaced,
        [EnumMember(Value = "Rejected")]
        Rejected
    }
    internal static class OrderStatusEnumExtension
    {
        internal static string ToSerializedValue(this OrderStatus? value)
        {
            return value == null ? null : ((OrderStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderStatus value)
        {
            switch( value )
            {
                case OrderStatus.Unknown:
                    return "Unknown";
                case OrderStatus.Placed:
                    return "Placed";
                case OrderStatus.PartiallyMatched:
                    return "PartiallyMatched";
                case OrderStatus.Matched:
                    return "Matched";
                case OrderStatus.Pending:
                    return "Pending";
                case OrderStatus.Cancelled:
                    return "Cancelled";
                case OrderStatus.Replaced:
                    return "Replaced";
                case OrderStatus.Rejected:
                    return "Rejected";
            }
            return null;
        }

        internal static OrderStatus? ParseOrderStatus(this string value)
        {
            switch( value )
            {
                case "Unknown":
                    return OrderStatus.Unknown;
                case "Placed":
                    return OrderStatus.Placed;
                case "PartiallyMatched":
                    return OrderStatus.PartiallyMatched;
                case "Matched":
                    return OrderStatus.Matched;
                case "Pending":
                    return OrderStatus.Pending;
                case "Cancelled":
                    return OrderStatus.Cancelled;
                case "Replaced":
                    return OrderStatus.Replaced;
                case "Rejected":
                    return OrderStatus.Rejected;
            }
            return null;
        }
    }
}
