// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Request model for placing new market orders.
    /// </summary>
    public partial class PlaceMarketOrderModel
    {
        /// <summary>
        /// Initializes a new instance of the PlaceMarketOrderModel class.
        /// </summary>
        public PlaceMarketOrderModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlaceMarketOrderModel class.
        /// </summary>
        /// <param name="assetPairId">The asset pair identifier, eg
        /// BTCUSD.</param>
        /// <param name="asset">The asset that you want to buy or sell, eg BTC
        /// in case of BTCUSD.</param>
        /// <param name="orderAction">The type of order (Buy or Sell). Possible
        /// values include: 'Buy', 'Sell'</param>
        /// <param name="volume">The amount of the asset you want to buy or
        /// sell, should be at least the minimum volume of the asset
        /// pair.</param>
        public PlaceMarketOrderModel(string assetPairId, string asset, OrderAction orderAction, double volume)
        {
            AssetPairId = assetPairId;
            Asset = asset;
            OrderAction = orderAction;
            Volume = volume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the asset pair identifier, eg BTCUSD.
        /// </summary>
        [JsonProperty(PropertyName = "AssetPairId")]
        public string AssetPairId { get; set; }

        /// <summary>
        /// Gets or sets the asset that you want to buy or sell, eg BTC in case
        /// of BTCUSD.
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// Gets or sets the type of order (Buy or Sell). Possible values
        /// include: 'Buy', 'Sell'
        /// </summary>
        [JsonProperty(PropertyName = "OrderAction")]
        public OrderAction OrderAction { get; set; }

        /// <summary>
        /// Gets or sets the amount of the asset you want to buy or sell,
        /// should be at least the minimum volume of the asset pair.
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AssetPairId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AssetPairId");
            }
            if (Asset == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Asset");
            }
        }
    }
}
