// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;

    /// <summary>
    /// Request model for placing new stop limit orders.
    /// </summary>
    public partial class PlaceStopLimitOrderModel
    {
        /// <summary>
        /// Initializes a new instance of the PlaceStopLimitOrderModel class.
        /// </summary>
        public PlaceStopLimitOrderModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlaceStopLimitOrderModel class.
        /// </summary>
        /// <param name="assetPairId">The asset pair you want to buy or
        /// sell.</param>
        /// <param name="orderAction">The order action you want to perform (Buy
        /// or Sell). Possible values include: 'Buy', 'Sell'</param>
        /// <param name="volume">The amount of the asset you want to buy or
        /// sell, should be at least the minimum volume of the asset
        /// pair.</param>
        /// <param name="lowerLimitPrice">The lower limit price for this stop
        /// order.</param>
        /// <param name="lowerPrice">The lower price for this stop
        /// order.</param>
        /// <param name="upperLimitPrice">The upper limit price for this stop
        /// order.</param>
        /// <param name="upperPrice">The upper price for this stop
        /// order.</param>
        public PlaceStopLimitOrderModel(string assetPairId, OrderAction orderAction, double volume, double lowerLimitPrice, double lowerPrice, double upperLimitPrice, double upperPrice)
        {
            AssetPairId = assetPairId;
            OrderAction = orderAction;
            Volume = volume;
            LowerLimitPrice = lowerLimitPrice;
            LowerPrice = lowerPrice;
            UpperLimitPrice = upperLimitPrice;
            UpperPrice = upperPrice;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the asset pair you want to buy or sell.
        /// </summary>
        [JsonProperty(PropertyName = "AssetPairId")]
        public string AssetPairId { get; set; }

        /// <summary>
        /// Gets or sets the order action you want to perform (Buy or Sell).
        /// Possible values include: 'Buy', 'Sell'
        /// </summary>
        [JsonProperty(PropertyName = "OrderAction")]
        public OrderAction OrderAction { get; set; }

        /// <summary>
        /// Gets or sets the amount of the asset you want to buy or sell,
        /// should be at least the minimum volume of the asset pair.
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// Gets or sets the lower limit price for this stop order.
        /// </summary>
        [JsonProperty(PropertyName = "LowerLimitPrice")]
        public double LowerLimitPrice { get; set; }

        /// <summary>
        /// Gets or sets the lower price for this stop order.
        /// </summary>
        [JsonProperty(PropertyName = "LowerPrice")]
        public double LowerPrice { get; set; }

        /// <summary>
        /// Gets or sets the upper limit price for this stop order.
        /// </summary>
        [JsonProperty(PropertyName = "UpperLimitPrice")]
        public double UpperLimitPrice { get; set; }

        /// <summary>
        /// Gets or sets the upper price for this stop order.
        /// </summary>
        [JsonProperty(PropertyName = "UpperPrice")]
        public double UpperPrice { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AssetPairId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AssetPairId");
            }
        }
    }
}
