// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Side.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Side
    {
        [EnumMember(Value = "Both")]
        Both,
        [EnumMember(Value = "Buy")]
        Buy,
        [EnumMember(Value = "Sell")]
        Sell
    }
    internal static class SideEnumExtension
    {
        internal static string ToSerializedValue(this Side? value)
        {
            return value == null ? null : ((Side)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Side value)
        {
            switch( value )
            {
                case Side.Both:
                    return "Both";
                case Side.Buy:
                    return "Buy";
                case Side.Sell:
                    return "Sell";
            }
            return null;
        }

        internal static Side? ParseSide(this string value)
        {
            switch( value )
            {
                case "Both":
                    return Side.Both;
                case "Buy":
                    return Side.Buy;
                case "Sell":
                    return Side.Sell;
            }
            return null;
        }
    }
}
