// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BroadcastTransactionResponse
    {
        /// <summary>
        /// Initializes a new instance of the BroadcastTransactionResponse
        /// class.
        /// </summary>
        public BroadcastTransactionResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BroadcastTransactionResponse
        /// class.
        /// </summary>
        /// <param name="errorCode">Possible values include: 'unknown',
        /// 'amountIsTooSmall', 'notEnoughtBalance'</param>
        public BroadcastTransactionResponse(TransactionExecutionError? errorCode = default(TransactionExecutionError?))
        {
            ErrorCode = errorCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'unknown',
        /// 'amountIsTooSmall', 'notEnoughtBalance'
        /// </summary>
        [JsonProperty(PropertyName = "errorCode")]
        public TransactionExecutionError? ErrorCode { get; set; }

    }
}
