// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BroadcastedTransactionResponse
    {
        /// <summary>
        /// Initializes a new instance of the BroadcastedTransactionResponse
        /// class.
        /// </summary>
        public BroadcastedTransactionResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BroadcastedTransactionResponse
        /// class.
        /// </summary>
        /// <param name="state">Possible values include: 'InProgress',
        /// 'Completed', 'Failed'</param>
        public BroadcastedTransactionResponse(System.Guid operationId, BroadcastedTransactionState state, System.DateTime timestamp, string amount = default(string), string fee = default(string), string hash = default(string), string error = default(string), string errorCode = default(string), long block = default(long))
        {
            OperationId = operationId;
            State = state;
            Timestamp = timestamp;
            Amount = amount;
            Fee = fee;
            Hash = hash;
            Error = error;
            ErrorCode = errorCode;
            Block = block;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operationId")]
        public System.Guid OperationId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'InProgress', 'Completed',
        /// 'Failed'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public BroadcastedTransactionState State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public string Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fee")]
        public string Fee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hash")]
        public string Hash { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

        [JsonProperty(PropertyName = "errorCode")]
        public string ErrorCode { get; set; }

        [JsonProperty(PropertyName = "block")]
        public long Block { get; set; }
        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
