// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BuildTransactionResponse
    {
        /// <summary>
        /// Initializes a new instance of the BuildTransactionResponse class.
        /// </summary>
        public BuildTransactionResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BuildTransactionResponse class.
        /// </summary>
        /// <param name="errorCode">Possible values include: 'unknown',
        /// 'amountIsTooSmall', 'notEnoughtBalance'</param>
        public BuildTransactionResponse(TransactionExecutionError? errorCode = default(TransactionExecutionError?), string transactionContext = default(string))
        {
            ErrorCode = errorCode;
            TransactionContext = transactionContext;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'unknown',
        /// 'amountIsTooSmall', 'notEnoughtBalance'
        /// </summary>
        [JsonProperty(PropertyName = "errorCode")]
        public TransactionExecutionError? ErrorCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionContext")]
        public string TransactionContext { get; set; }

    }
}
