// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ApiAssetPairRateModel
    {
        /// <summary>
        /// Initializes a new instance of the ApiAssetPairRateModel class.
        /// </summary>
        public ApiAssetPairRateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiAssetPairRateModel class.
        /// </summary>
        public ApiAssetPairRateModel(double? pChng = default(double?), IList<double?> chngGrph = default(IList<double?>), bool? inverted = default(bool?), string id = default(string), double? bid = default(double?), double? ask = default(double?))
        {
            PChng = pChng;
            ChngGrph = chngGrph;
            Inverted = inverted;
            Id = id;
            Bid = bid;
            Ask = ask;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PChng")]
        public double? PChng { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChngGrph")]
        public IList<double?> ChngGrph { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Inverted")]
        public bool? Inverted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Bid")]
        public double? Bid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Ask")]
        public double? Ask { get; set; }

    }
}
