// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApiBlockchainTransaction
    {
        /// <summary>
        /// Initializes a new instance of the ApiBlockchainTransaction class.
        /// </summary>
        public ApiBlockchainTransaction()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiBlockchainTransaction class.
        /// </summary>
        public ApiBlockchainTransaction(string hash = default(string), string date = default(string), int? confirmations = default(int?), string block = default(string), int? height = default(int?), string senderId = default(string), string assetId = default(string), string quantity = default(string), string url = default(string))
        {
            Hash = hash;
            Date = date;
            Confirmations = confirmations;
            Block = block;
            Height = height;
            SenderId = senderId;
            AssetId = assetId;
            Quantity = quantity;
            Url = url;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Hash")]
        public string Hash { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public string Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Confirmations")]
        public int? Confirmations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Block")]
        public string Block { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Height")]
        public int? Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SenderId")]
        public string SenderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quantity")]
        public string Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

    }
}
