// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApiBalanceRecord
    {
        /// <summary>
        /// Initializes a new instance of the ApiBalanceRecord class.
        /// </summary>
        public ApiBalanceRecord()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiBalanceRecord class.
        /// </summary>
        public ApiBalanceRecord(string assetId = default(string), double? balance = default(double?), string baseAssetId = default(string), double? amountInBase = default(double?))
        {
            AssetId = assetId;
            Balance = balance;
            BaseAssetId = baseAssetId;
            AmountInBase = amountInBase;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Balance")]
        public double? Balance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseAssetId")]
        public string BaseAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AmountInBase")]
        public double? AmountInBase { get; set; }

    }
}
