// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApiTransaction
    {
        /// <summary>
        /// Initializes a new instance of the ApiTransaction class.
        /// </summary>
        public ApiTransaction()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiTransaction class.
        /// </summary>
        public ApiTransaction(string id = default(string), string hex = default(string))
        {
            Id = id;
            Hex = hex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Hex")]
        public string Hex { get; set; }

    }
}
