// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetWithAmount
    {
        /// <summary>
        /// Initializes a new instance of the AssetWithAmount class.
        /// </summary>
        public AssetWithAmount()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetWithAmount class.
        /// </summary>
        public AssetWithAmount(string assetId = default(string), double? amount = default(double?))
        {
            AssetId = assetId;
            Amount = amount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

    }
}
