// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AuthenticateResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the AuthenticateResponseModel class.
        /// </summary>
        public AuthenticateResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AuthenticateResponseModel class.
        /// </summary>
        /// <param name="kycStatus">Possible values include: 'NeedToFillData',
        /// 'Pending', 'Ok', 'RestrictedArea'</param>
        public AuthenticateResponseModel(string kycStatus = default(string), bool? pinIsEntered = default(bool?), string token = default(string), string notificationsId = default(string), ApiPersonalDataModel personalData = default(ApiPersonalDataModel), bool? canCashInViaBankCard = default(bool?), bool? swiftDepositEnabled = default(bool?), bool? isUserFromUSA = default(bool?))
        {
            KycStatus = kycStatus;
            PinIsEntered = pinIsEntered;
            Token = token;
            NotificationsId = notificationsId;
            PersonalData = personalData;
            CanCashInViaBankCard = canCashInViaBankCard;
            SwiftDepositEnabled = swiftDepositEnabled;
            IsUserFromUSA = isUserFromUSA;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'NeedToFillData', 'Pending',
        /// 'Ok', 'RestrictedArea'
        /// </summary>
        [JsonProperty(PropertyName = "KycStatus")]
        public string KycStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PinIsEntered")]
        public bool? PinIsEntered { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Token")]
        public string Token { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NotificationsId")]
        public string NotificationsId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PersonalData")]
        public ApiPersonalDataModel PersonalData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CanCashInViaBankCard")]
        public bool? CanCashInViaBankCard { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SwiftDepositEnabled")]
        public bool? SwiftDepositEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsUserFromUSA")]
        public bool? IsUserFromUSA { get; set; }

    }
}
