// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BankCardPaymentUrlResponceModel
    {
        /// <summary>
        /// Initializes a new instance of the BankCardPaymentUrlResponceModel
        /// class.
        /// </summary>
        public BankCardPaymentUrlResponceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BankCardPaymentUrlResponceModel
        /// class.
        /// </summary>
        public BankCardPaymentUrlResponceModel(string url = default(string), string okUrl = default(string), string failUrl = default(string), string reloadRegex = default(string), string urlsToFormatRegex = default(string))
        {
            Url = url;
            OkUrl = okUrl;
            FailUrl = failUrl;
            ReloadRegex = reloadRegex;
            UrlsToFormatRegex = urlsToFormatRegex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OkUrl")]
        public string OkUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FailUrl")]
        public string FailUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReloadRegex")]
        public string ReloadRegex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UrlsToFormatRegex")]
        public string UrlsToFormatRegex { get; set; }

    }
}
