// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BlockchainAddressValidityResponseModel
    {
        public BlockchainAddressValidityResponseModel()
        { }
        public Result Result { get; set; }
        public object Error { get; set; }
    }

    public class Result
    {
        public bool IsValid { get; set; }
    }

}
