// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BlockchainAddressValidityResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// BlockchainAddressValidityResponseModel class.
        /// </summary>
        public BlockchainAddressValidityResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// BlockchainAddressValidityResponseModel class.
        /// </summary>
        public BlockchainAddressValidityResponseModel(bool? isValid = default(bool?))
        {
            IsValid = isValid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsValid")]
        public bool? IsValid { get; set; }

    }
}
