// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CashOutPostModel
    {
        /// <summary>
        /// Initializes a new instance of the CashOutPostModel class.
        /// </summary>
        public CashOutPostModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CashOutPostModel class.
        /// </summary>
        public CashOutPostModel(string multiSig = default(string), double? amount = default(double?), string assetId = default(string))
        {
            MultiSig = multiSig;
            Amount = amount;
            AssetId = assetId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MultiSig")]
        public string MultiSig { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

    }
}
