// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConversionResult
    {
        /// <summary>
        /// Initializes a new instance of the ConversionResult class.
        /// </summary>
        public ConversionResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConversionResult class.
        /// </summary>
        /// <param name="result">Possible values include: 'Unknown', 'Ok',
        /// 'InvalidInputParameters', 'NoLiquidity'</param>
        public ConversionResult(AssetWithAmount fromProperty = default(AssetWithAmount), AssetWithAmount to = default(AssetWithAmount), double? price = default(double?), double? volumePrice = default(double?), string result = default(string))
        {
            FromProperty = fromProperty;
            To = to;
            Price = price;
            VolumePrice = volumePrice;
            Result = result;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "From")]
        public AssetWithAmount FromProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "To")]
        public AssetWithAmount To { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VolumePrice")]
        public double? VolumePrice { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Ok',
        /// 'InvalidInputParameters', 'NoLiquidity'
        /// </summary>
        [JsonProperty(PropertyName = "Result")]
        public string Result { get; set; }

    }
}
