// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreditVoucherFormattedContent
    {
        /// <summary>
        /// Initializes a new instance of the CreditVoucherFormattedContent
        /// class.
        /// </summary>
        public CreditVoucherFormattedContent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreditVoucherFormattedContent
        /// class.
        /// </summary>
        public CreditVoucherFormattedContent(string formattedContentBase64 = default(string))
        {
            FormattedContentBase64 = formattedContentBase64;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FormattedContentBase64")]
        public string FormattedContentBase64 { get; set; }

    }
}
