// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CustomWatchListCreateModel
    {
        /// <summary>
        /// Initializes a new instance of the CustomWatchListCreateModel class.
        /// </summary>
        public CustomWatchListCreateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomWatchListCreateModel class.
        /// </summary>
        public CustomWatchListCreateModel(string name = default(string), int? order = default(int?), IList<string> assetIds = default(IList<string>))
        {
            Name = name;
            Order = order;
            AssetIds = assetIds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Order")]
        public int? Order { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetIds")]
        public IList<string> AssetIds { get; set; }

    }
}
