// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EncodedKeyModel
    {
        /// <summary>
        /// Initializes a new instance of the EncodedKeyModel class.
        /// </summary>
        public EncodedKeyModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EncodedKeyModel class.
        /// </summary>
        public EncodedKeyModel(string encodedPrivateKey = default(string))
        {
            EncodedPrivateKey = encodedPrivateKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EncodedPrivateKey")]
        public string EncodedPrivateKey { get; set; }

    }
}
