// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EthereumAssetResponse
    {
        /// <summary>
        /// Initializes a new instance of the EthereumAssetResponse class.
        /// </summary>
        public EthereumAssetResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EthereumAssetResponse class.
        /// </summary>
        public EthereumAssetResponse(int? stepsCount = default(int?), string ethAssetId = default(string), string stepGas = default(string))
        {
            StepsCount = stepsCount;
            EthAssetId = ethAssetId;
            StepGas = stepGas;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StepsCount")]
        public int? StepsCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EthAssetId")]
        public string EthAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StepGas")]
        public string StepGas { get; set; }

    }
}
