// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EthereumTransactionResponseContainer
    {
        /// <summary>
        /// Initializes a new instance of the
        /// EthereumTransactionResponseContainer class.
        /// </summary>
        public EthereumTransactionResponseContainer()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// EthereumTransactionResponseContainer class.
        /// </summary>
        public EthereumTransactionResponseContainer(EthereumTransactionHistoricalResponse transaction = default(EthereumTransactionHistoricalResponse), IList<EthereumInternalMessageHistoricalResponse> messages = default(IList<EthereumInternalMessageHistoricalResponse>), IList<ErcEthPrivateWalletHistoryRecord> ercTransfers = default(IList<ErcEthPrivateWalletHistoryRecord>))
        {
            Transaction = transaction;
            Messages = messages;
            ErcTransfers = ercTransfers;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Transaction")]
        public EthereumTransactionHistoricalResponse Transaction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Messages")]
        public IList<EthereumInternalMessageHistoricalResponse> Messages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErcTransfers")]
        public IList<ErcEthPrivateWalletHistoryRecord> ErcTransfers { get; set; }

    }
}
