// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EthereumEmptyTransactionModel
    {
        /// <summary>
        /// Initializes a new instance of the EthereumEmptyTransactionModel
        /// class.
        /// </summary>
        public EthereumEmptyTransactionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EthereumEmptyTransactionModel
        /// class.
        /// </summary>
        public EthereumEmptyTransactionModel(System.Guid? id = default(System.Guid?), string hash = default(string))
        {
            Id = id;
            Hash = hash;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Hash")]
        public string Hash { get; set; }

    }
}
