// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EthTransaction
    {
        /// <summary>
        /// Initializes a new instance of the EthTransaction class.
        /// </summary>
        public EthTransaction()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EthTransaction class.
        /// </summary>
        public EthTransaction(string fromProperty = default(string), string hex = default(string))
        {
            FromProperty = fromProperty;
            Hex = hex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "From")]
        public string FromProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Hex")]
        public string Hex { get; set; }

    }
}
