// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FeeSettings
    {
        /// <summary>
        /// Initializes a new instance of the FeeSettings class.
        /// </summary>
        public FeeSettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FeeSettings class.
        /// </summary>
        public FeeSettings(double? bankCardsFeeSizePercentage = default(double?))
        {
            BankCardsFeeSizePercentage = bankCardsFeeSizePercentage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BankCardsFeeSizePercentage")]
        public double? BankCardsFeeSizePercentage { get; set; }

    }
}
