// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetAllAssetPairsRatesModel
    {
        /// <summary>
        /// Initializes a new instance of the GetAllAssetPairsRatesModel class.
        /// </summary>
        public GetAllAssetPairsRatesModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetAllAssetPairsRatesModel class.
        /// </summary>
        public GetAllAssetPairsRatesModel(IList<ApiAssetPairRateBaseModel> rates = default(IList<ApiAssetPairRateBaseModel>))
        {
            Rates = rates;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Rates")]
        public IList<ApiAssetPairRateBaseModel> Rates { get; set; }

    }
}
