// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetMyLykkeInfoRespModel
    {
        /// <summary>
        /// Initializes a new instance of the GetMyLykkeInfoRespModel class.
        /// </summary>
        public GetMyLykkeInfoRespModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetMyLykkeInfoRespModel class.
        /// </summary>
        public GetMyLykkeInfoRespModel(int? lkkTotalAmount = default(int?), int? lkkBalance = default(int?), string btcConversionWalletAddress = default(string), int? numberOfShares = default(int?), double? marketValueUSD = default(double?), double? myEquityPercent = default(double?))
        {
            LkkTotalAmount = lkkTotalAmount;
            LkkBalance = lkkBalance;
            BtcConversionWalletAddress = btcConversionWalletAddress;
            NumberOfShares = numberOfShares;
            MarketValueUSD = marketValueUSD;
            MyEquityPercent = myEquityPercent;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LkkTotalAmount")]
        public int? LkkTotalAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LkkBalance")]
        public int? LkkBalance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BtcConversionWalletAddress")]
        public string BtcConversionWalletAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfShares")]
        public int? NumberOfShares { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarketValueUSD")]
        public double? MarketValueUSD { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MyEquityPercent")]
        public double? MyEquityPercent { get; set; }

    }
}
