// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetWaletsRespModel
    {
        /// <summary>
        /// Initializes a new instance of the GetWaletsRespModel class.
        /// </summary>
        public GetWaletsRespModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetWaletsRespModel class.
        /// </summary>
        public GetWaletsRespModel(LykkeWalletsModel lykke = default(LykkeWalletsModel), IList<ApiBankCardModel> bankCards = default(IList<ApiBankCardModel>), string multiSig = default(string), string coloredMultiSig = default(string), string solarCoinAddress = default(string))
        {
            Lykke = lykke;
            BankCards = bankCards;
            MultiSig = multiSig;
            ColoredMultiSig = coloredMultiSig;
            SolarCoinAddress = solarCoinAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Lykke")]
        public LykkeWalletsModel Lykke { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BankCards")]
        public IList<ApiBankCardModel> BankCards { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MultiSig")]
        public string MultiSig { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ColoredMultiSig")]
        public string ColoredMultiSig { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SolarCoinAddress")]
        public string SolarCoinAddress { get; set; }

    }
}
