// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HotWalletLimitOperation
    {
        /// <summary>
        /// Initializes a new instance of the HotWalletLimitOperation class.
        /// </summary>
        public HotWalletLimitOperation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HotWalletLimitOperation class.
        /// </summary>
        public HotWalletLimitOperation(double? price = default(double?), string assetPair = default(string), string assetId = default(string), double? volume = default(double?))
        {
            Price = price;
            AssetPair = assetPair;
            AssetId = assetId;
            Volume = volume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double? Volume { get; set; }

    }
}
