// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HotWalletCashoutOperation
    {
        /// <summary>
        /// Initializes a new instance of the HotWalletCashoutOperation class.
        /// </summary>
        public HotWalletCashoutOperation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HotWalletCashoutOperation class.
        /// </summary>
        public HotWalletCashoutOperation(string destinationAddressExtension = default(string), string destinationAddress = default(string), string assetId = default(string), double? volume = default(double?))
        {
            DestinationAddressExtension = destinationAddressExtension;
            DestinationAddress = destinationAddress;
            AssetId = assetId;
            Volume = volume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DestinationAddressExtension ")]
        public string DestinationAddressExtension { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DestinationAddress")]
        public string DestinationAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double? Volume { get; set; }

    }
}
