// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class IFormFile
    {
        /// <summary>
        /// Initializes a new instance of the IFormFile class.
        /// </summary>
        public IFormFile()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IFormFile class.
        /// </summary>
        public IFormFile(string contentType = default(string), string contentDisposition = default(string), IDictionary<string, IList<string>> headers = default(IDictionary<string, IList<string>>), long? length = default(long?), string name = default(string), string fileName = default(string))
        {
            ContentType = contentType;
            ContentDisposition = contentDisposition;
            Headers = headers;
            Length = length;
            Name = name;
            FileName = fileName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContentType")]
        public string ContentType { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContentDisposition")]
        public string ContentDisposition { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Headers")]
        public IDictionary<string, IList<string>> Headers { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Length")]
        public long? Length { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileName")]
        public string FileName { get; private set; }

    }
}
