// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IsPinSecurityEnabledResultModel
    {
        /// <summary>
        /// Initializes a new instance of the IsPinSecurityEnabledResultModel
        /// class.
        /// </summary>
        public IsPinSecurityEnabledResultModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IsPinSecurityEnabledResultModel
        /// class.
        /// </summary>
        public IsPinSecurityEnabledResultModel(bool? isEnabled = default(bool?))
        {
            IsEnabled = isEnabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsEnabled")]
        public bool? IsEnabled { get; set; }

    }
}
