// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ObsoletteDictsRespModel
    {
        /// <summary>
        /// Initializes a new instance of the ObsoletteDictsRespModel class.
        /// </summary>
        public ObsoletteDictsRespModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ObsoletteDictsRespModel class.
        /// </summary>
        public ObsoletteDictsRespModel(IList<ObsoleteApiDictAsset> assets = default(IList<ObsoleteApiDictAsset>))
        {
            Assets = assets;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Assets")]
        public IList<ObsoleteApiDictAsset> Assets { get; set; }

    }
}
