// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OffchainLimitOrdersRespModel
    {
        /// <summary>
        /// Initializes a new instance of the OffchainLimitOrdersRespModel
        /// class.
        /// </summary>
        public OffchainLimitOrdersRespModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainLimitOrdersRespModel
        /// class.
        /// </summary>
        public OffchainLimitOrdersRespModel(IList<ApiOffchainOrder> orders = default(IList<ApiOffchainOrder>))
        {
            Orders = orders;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Orders")]
        public IList<ApiOffchainOrder> Orders { get; set; }

    }
}
