// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainTradeModel
    {
        /// <summary>
        /// Initializes a new instance of the OffchainTradeModel class.
        /// </summary>
        public OffchainTradeModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainTradeModel class.
        /// </summary>
        public OffchainTradeModel(string assetPair = default(string), string asset = default(string), double? volume = default(double?), string prevTempPrivateKey = default(string))
        {
            AssetPair = assetPair;
            Asset = asset;
            Volume = volume;
            PrevTempPrivateKey = prevTempPrivateKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double? Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrevTempPrivateKey")]
        public string PrevTempPrivateKey { get; set; }

    }
}
