// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainTransferToMarginModel
    {
        /// <summary>
        /// Initializes a new instance of the OffchainTransferToMarginModel
        /// class.
        /// </summary>
        public OffchainTransferToMarginModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainTransferToMarginModel
        /// class.
        /// </summary>
        public OffchainTransferToMarginModel(string accountId = default(string), double? amount = default(double?), string prevTempPrivateKey = default(string))
        {
            AccountId = accountId;
            Amount = amount;
            PrevTempPrivateKey = prevTempPrivateKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrevTempPrivateKey")]
        public string PrevTempPrivateKey { get; set; }

    }
}
