// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainRequestTransferModel
    {
        /// <summary>
        /// Initializes a new instance of the OffchainRequestTransferModel
        /// class.
        /// </summary>
        public OffchainRequestTransferModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainRequestTransferModel
        /// class.
        /// </summary>
        public OffchainRequestTransferModel(string requestId = default(string), string prevTempPrivateKey = default(string))
        {
            RequestId = requestId;
            PrevTempPrivateKey = prevTempPrivateKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequestId")]
        public string RequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrevTempPrivateKey")]
        public string PrevTempPrivateKey { get; set; }

    }
}
