// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OperationCollectionModel
    {
        /// <summary>
        /// Initializes a new instance of the OperationCollectionModel class.
        /// </summary>
        public OperationCollectionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OperationCollectionModel class.
        /// </summary>
        public OperationCollectionModel(IList<OperationModel> operations = default(IList<OperationModel>))
        {
            Operations = operations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Operations")]
        public IList<OperationModel> Operations { get; set; }

    }
}
