// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PostClientCountryModel
    {
        /// <summary>
        /// Initializes a new instance of the PostClientCountryModel class.
        /// </summary>
        public PostClientCountryModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostClientCountryModel class.
        /// </summary>
        public PostClientCountryModel(string country = default(string))
        {
            Country = country;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

    }
}
