// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PostKycDocumentRespModel
    {
        /// <summary>
        /// Initializes a new instance of the PostKycDocumentRespModel class.
        /// </summary>
        public PostKycDocumentRespModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostKycDocumentRespModel class.
        /// </summary>
        public PostKycDocumentRespModel(ApiPersonalDataModel personalData = default(ApiPersonalDataModel))
        {
            PersonalData = personalData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PersonalData")]
        public ApiPersonalDataModel PersonalData { get; set; }

    }
}
