// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PostMyLykkeCashInEmailModel
    {
        /// <summary>
        /// Initializes a new instance of the PostMyLykkeCashInEmailModel
        /// class.
        /// </summary>
        public PostMyLykkeCashInEmailModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostMyLykkeCashInEmailModel
        /// class.
        /// </summary>
        public PostMyLykkeCashInEmailModel(string assetId = default(string), double? amount = default(double?), double? lkkAmount = default(double?), double? price = default(double?))
        {
            AssetId = assetId;
            Amount = amount;
            LkkAmount = lkkAmount;
            Price = price;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LkkAmount")]
        public double? LkkAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double? Price { get; set; }

    }
}
