// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PostRecoverySmsConfirmationModel
    {
        /// <summary>
        /// Initializes a new instance of the PostRecoverySmsConfirmationModel
        /// class.
        /// </summary>
        public PostRecoverySmsConfirmationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostRecoverySmsConfirmationModel
        /// class.
        /// </summary>
        public PostRecoverySmsConfirmationModel(string partnerId = default(string), string email = default(string), string signedOwnershipMsg = default(string))
        {
            PartnerId = partnerId;
            Email = email;
            SignedOwnershipMsg = signedOwnershipMsg;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerId")]
        public string PartnerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SignedOwnershipMsg")]
        public string SignedOwnershipMsg { get; set; }

    }
}
