// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PurchaseAssetRespModel
    {
        /// <summary>
        /// Initializes a new instance of the PurchaseAssetRespModel class.
        /// </summary>
        public PurchaseAssetRespModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PurchaseAssetRespModel class.
        /// </summary>
        public PurchaseAssetRespModel(ApiMarketOrder order = default(ApiMarketOrder), IList<ApiTradeOperation> trades = default(IList<ApiTradeOperation>))
        {
            Order = order;
            Trades = trades;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Order")]
        public ApiMarketOrder Order { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Trades")]
        public IList<ApiTradeOperation> Trades { get; set; }

    }
}
