// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SetKeyModel
    {
        /// <summary>
        /// Initializes a new instance of the SetKeyModel class.
        /// </summary>
        public SetKeyModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SetKeyModel class.
        /// </summary>
        public SetKeyModel(string address = default(string), string encodedKey = default(string))
        {
            Address = address;
            EncodedKey = encodedKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EncodedKey")]
        public string EncodedKey { get; set; }

    }
}
