// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SignedRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the SignedRequestModel class.
        /// </summary>
        public SignedRequestModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SignedRequestModel class.
        /// </summary>
        public SignedRequestModel(System.Guid? requestId = default(System.Guid?), string multisigAddress = default(string), string sign = default(string))
        {
            RequestId = requestId;
            MultisigAddress = multisigAddress;
            Sign = sign;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequestId")]
        public System.Guid? RequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MultisigAddress")]
        public string MultisigAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sign")]
        public string Sign { get; set; }

    }
}
