// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TermsOfUseModel
    {
        /// <summary>
        /// Initializes a new instance of the TermsOfUseModel class.
        /// </summary>
        public TermsOfUseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TermsOfUseModel class.
        /// </summary>
        public TermsOfUseModel(string spotTermsOfUseLink = default(string), string marginTermsOfUseLink = default(string), string marginRiskDescriptionLink = default(string))
        {
            SpotTermsOfUseLink = spotTermsOfUseLink;
            MarginTermsOfUseLink = marginTermsOfUseLink;
            MarginRiskDescriptionLink = marginRiskDescriptionLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SpotTermsOfUseLink")]
        public string SpotTermsOfUseLink { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarginTermsOfUseLink")]
        public string MarginTermsOfUseLink { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarginRiskDescriptionLink")]
        public string MarginRiskDescriptionLink { get; set; }

    }
}
