// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransactionHashModel
    {
        /// <summary>
        /// Initializes a new instance of the TransactionHashModel class.
        /// </summary>
        public TransactionHashModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionHashModel class.
        /// </summary>
        public TransactionHashModel(string transactionHash = default(string))
        {
            TransactionHash = transactionHash;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransactionHash")]
        public string TransactionHash { get; set; }

    }
}
