// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SignTransactionResponse
    {
        /// <summary>
        /// Initializes a new instance of the SignTransactionResponse class.
        /// </summary>
        public SignTransactionResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SignTransactionResponse class.
        /// </summary>
        public SignTransactionResponse(string signedTransaction = default(string))
        {
            SignedTransaction = signedTransaction;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "signedTransaction")]
        public string SignedTransaction { get; set; }

    }
}
