// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetPairResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetPairResponseModel class.
        /// </summary>
        public AssetPairResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetPairResponseModel class.
        /// </summary>
        public AssetPairResponseModel(int accuracy, int invertedAccuracy, bool isDisabled, string id = default(string), string name = default(string), string baseAssetId = default(string), string quotingAssetId = default(string), string source = default(string), string source2 = default(string))
        {
            Id = id;
            Name = name;
            BaseAssetId = baseAssetId;
            QuotingAssetId = quotingAssetId;
            Accuracy = accuracy;
            InvertedAccuracy = invertedAccuracy;
            Source = source;
            Source2 = source2;
            IsDisabled = isDisabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseAssetId")]
        public string BaseAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuotingAssetId")]
        public string QuotingAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Accuracy")]
        public int Accuracy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvertedAccuracy")]
        public int InvertedAccuracy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Source2")]
        public string Source2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsDisabled")]
        public bool IsDisabled { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
