// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents an asset default condition layer.
    /// </summary>
    public partial class AssetDefaultConditionLayerModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetDefaultConditionLayerModel
        /// class.
        /// </summary>
        public AssetDefaultConditionLayerModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetDefaultConditionLayerModel
        /// class.
        /// </summary>
        /// <param name="id">The layer id.</param>
        /// <param name="clientsCanCashInViaBankCards">The client ability to
        /// cash in via bank cards.</param>
        /// <param name="swiftDepositEnabled">The client ability to swift
        /// deposit.</param>
        /// <param name="assetConditions">The collection of asset conditions
        /// for layer.</param>
        public AssetDefaultConditionLayerModel(string id = default(string), bool? clientsCanCashInViaBankCards = default(bool?), bool? swiftDepositEnabled = default(bool?), IList<AssetConditionModel> assetConditions = default(IList<AssetConditionModel>))
        {
            Id = id;
            ClientsCanCashInViaBankCards = clientsCanCashInViaBankCards;
            SwiftDepositEnabled = swiftDepositEnabled;
            AssetConditions = assetConditions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the layer id.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the client ability to cash in via bank cards.
        /// </summary>
        [JsonProperty(PropertyName = "ClientsCanCashInViaBankCards")]
        public bool? ClientsCanCashInViaBankCards { get; set; }

        /// <summary>
        /// Gets or sets the client ability to swift deposit.
        /// </summary>
        [JsonProperty(PropertyName = "SwiftDepositEnabled")]
        public bool? SwiftDepositEnabled { get; set; }

        /// <summary>
        /// Gets or sets the collection of asset conditions for layer.
        /// </summary>
        [JsonProperty(PropertyName = "AssetConditions")]
        public IList<AssetConditionModel> AssetConditions { get; set; }

    }
}
