// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AssetAttributes
    {
        /// <summary>
        /// Initializes a new instance of the AssetAttributes class.
        /// </summary>
        public AssetAttributes()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetAttributes class.
        /// </summary>
        public AssetAttributes(string assetId = default(string), IList<AssetAttribute> attributes = default(IList<AssetAttribute>))
        {
            AssetId = assetId;
            Attributes = attributes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attributes")]
        public IList<AssetAttribute> Attributes { get; set; }

    }
}
